### ISSUE TITLE
setup.py does not fallback to using distutils.core import setup

### ISSUE THREAD

**Issue by allanhaywood** [jazzband/contextlib2#13]
In all of the setup.py scripts I have used before, the import for setup is like this:

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

Which allows it to fall back to distutils.core if setuptools is not available.

Is there a reason that this is missing from this projects setup.py?

Thanks.

**Comment by ncoghlan** [comment]
Only the fact that `setup.py bdist_wheel` only works with setuptools, and that was the original motivation for moving away from plain distutils.

I'd accept a PR to add the fallback, as the setup call itself doesn't rely on any setuptools features, so it should be enough to get `setup.py install` working again under plain distutils.

**Comment by allanhaywood** [comment]
Thanks. I submitted a PR, let me know if there is anything additional needed on my end.
