### ISSUE TITLE
asynccontextmanager as decorator

### ISSUE THREAD

**Issue by Fak3** [jazzband/contextlib2#19]
The contextmanager decorated function can be used as decorator for sync functions. But asynccontextmanager decorated function cannot be used as decorator for async function. It would be nice to allow it

**Comment by Fak3** [comment]
Alternatively, regular contextmanager decorated function could be taught to wrap async functions, so that wrapped function is also async:

```python
from contextlib import contextmanager @contextmanager def managed_resource():
    resource = acquire_resource() 
    try: 
        yield 
    finally:
        release_resource(resource)

@managed_resource
async def routine ():
     pass
```

**Comment by jayvdb** [comment]
Is this a distinct issue separate from https://github.com/jazzband/contextlib2/issues/12 ?

If it is a smaller more easily achieved part of the problem, and more feasible, it might warrant a separate issue, especially if you are interested in working on it.

**Comment by Fak3** [comment]
I don't see how it is related to #12
Unfortunately I don't have time to work on it just yet.

**Comment by ncoghlan** [comment]
@jayvdb This is more along the lines of https://bugs.python.org/issue37398 (looking at the way ContextDecorator interacts with coroutines), using contextlib2 in its original role as "try out ideas before we enshrine them forever in the standard library".

The only relationship with #12 is that contextlib2 would really need to catch up with the current state of the stdlib version before it could be used to try out new async API design ideas.

**Comment by ncoghlan** [comment]
As it turns out, Python 3.10 did add https://docs.python.org/dev/library/contextlib.html#contextlib.AsyncContextDecorator and adapted asynccontextmanager to use it, so this *is* covered by #12 after all.
