### ISSUE TITLE
Not up-to-date changelog

### ISSUE THREAD

**Issue by xavfernandez** [jazzband/contextlib2#24]
v0.6.0 has been released in https://github.com/jazzband/contextlib2/tree/v0.6.0 and https://pypi.org/project/contextlib2/0.6.0/ but https://github.com/jazzband/contextlib2/blob/v0.6.0/NEWS.rst#060-unreleased makes it seems otherwise.

**Comment by ncoghlan** [comment]
D'oh!

**Comment by ncoghlan** [comment]
Thanks for the heads up :)

**Comment by michaelwood** [comment]
Thanks for work on contextlib2, but releasing a ".post1" package onto pypi means people end up with unnecessary python package dependency problems that can trickle down from upstream packages:

` pip "Could not find a version that matches contextlib2==0.6.0,==0.6.0.post1`
