### ISSUE TITLE
Documentation is not rebuilding

### ISSUE THREAD

**Issue by atugushev** [jazzband/contextlib2#25]
Documentation https://contextlib2.readthedocs.io looks stalled. Latest release in history is `0.5.5 (2017-04-25)`.

**Comment by ncoghlan** [comment]
Thanks for the heads up! It appears the auto-update link with ReadTheDocs failed some time between 0.5.5 and 0.6.0, as I just triggered a build through the RTD admin UI, and that appears to have updated it.

I'm going to keep this open until I've checked the web hook settings (and also reconfigured the RTD build to use Py3 to run Sphinx)

**Comment by atugushev** [comment]
@ncoghlan thanks!

**Comment by ncoghlan** [comment]
RTD build automatically started for https://github.com/jazzband/contextlib2/commit/94f388196326273cf4a3f1e61eb7accc7c73de2c and I've reconfigured RTD to use Py3 for the build, so closing this as resolved.
