### ISSUE TITLE
backport the typeshed contextlib.pyi file and add a py.typed

### ISSUE THREAD

**Issue by graingert** [jazzband/contextlib2#33]

**Comment by ncoghlan** [comment]
Reviewing https://www.python.org/dev/peps/pep-0561/:
* convert distribution structure from `contextlib2.py` to `contextlib2/__init__.py`
* add `contextlib2/py.typed`
* copy the typeshed `contextlib.pyi` file in as `contextlib2/__init__.pyi`

**Comment by graingert** [comment]
You could alternatively maintain a types-contextlib2 package with the pyi file in

**Comment by ncoghlan** [comment]
True, but the pyi file isn't that big, and having to keep a second package in sync would be annoying.

**Comment by ncoghlan** [comment]
It turned out the other concrete benefit to shipping a natively typed package was being able to integrate a self-consistency check into the module CI: #37
