### ISSUE TITLE
Use mypy.stubtest in CI

### ISSUE THREAD

**Issue by ncoghlan** [jazzband/contextlib2#37]
(Derived from https://github.com/python/mypy/issues/5028#issuecomment-869001339)

The current mypy CI check just tests that the stub file is well formed, it doesn't test that the module API actually matches the type hinted stub API. Running `mypy.stubcheck` instead will fix that testing gap, but the failures need to be fixed first:

```
[ncoghlan@thechalk contextlib2]$ python3 -m mypy.stubtest contextlib2
error: contextlib2.ContextDecorator.refresh_cm is not present in stub
Stub:
MISSING
Runtime: at line 76 in file /home/ncoghlan/devel/contextlib2/contextlib2/__init__.py
<function ContextDecorator.refresh_cm at 0x7fd497b61dc0>

error: contextlib2.ContextStack is not present in stub
Stub:
MISSING
Runtime: at line 783 in file /home/ncoghlan/devel/contextlib2/contextlib2/__init__.py
<class 'contextlib2.ContextStack'>

error: contextlib2.nullcontext is not a function
Stub: at line 122
Overload(def [_T] (enter_result: _T`-1) -> typing.ContextManager[_T`-1], def () -> typing.ContextManager[None])
Runtime: at line 755 in file /home/ncoghlan/devel/contextlib2/contextlib2/__init__.py
<class 'contextlib2.nullcontext'>
```

**Comment by graingert** [comment]
@ncoghlan fixed nullcontext upstream https://github.com/python/typeshed/pull/5695#event-4943033366

It looks like mypy.stubcheck is going to force your decision on the deprecated attributes though

**Comment by hauntsaninja** [comment]
Note that stubtest can be used with an allowlist, in case you want to ignore certain definitions (see `stubtest --help`)

**Comment by ncoghlan** [comment]
I pulled in the latest typeshed update to resolve the nullcontext error, and added dev/mypy.allowlist to ignore the deprecated APIs (I see type checking failing for those as a feature rather than a bug).
